### PR TITLE
Add cone of uncertainty

### PR DESCRIPTION
**Pull request by zapplebee**

### CODE REVIEW

**Review by ryanmr — APPROVED** [review]

**Comment by ryanmr** [comment]
I'll build this later today and deploy it.

**Comment by jeschauer** [comment]
@zapplebee makes a pull request and @ryanmr approves it right away ... I see my station here.

**Comment by ryanmr** [comment]
We need to rethink the Serengeti portion of content. It's an in-joke
awaiting generalization.

**Comment by zapplebee** [comment]
⏱ 👀

**Comment by ryanmr** [comment]
#wontfix

...
...
...

kidding.

**Comment by ryanmr** [comment]
Sorry @zapplebee it's been 5 months. Will build this year.

**Pull request merged**
